# Build script for VideoGrouper installer

# Configuration — version is sourced from video_grouper/version.py (single master)
$BUILD_NUMBER = "0"
$SCRIPT_DIR = Split-Path -Parent $MyInvocation.MyCommand.Path
$INSTALLER_SCRIPT = Join-Path $SCRIPT_DIR "video_grouper\installer\installer.nsi"
$DIST_DIR = Join-Path $SCRIPT_DIR "video_grouper\dist"
$BUILD_DIR = Join-Path $SCRIPT_DIR "video_grouper\build"

# Ensure we're in the correct directory
Set-Location $SCRIPT_DIR

# Create dist and build directories if they don't exist
if (-not (Test-Path $DIST_DIR)) {
    New-Item -ItemType Directory -Path $DIST_DIR
}
if (-not (Test-Path $BUILD_DIR)) {
    New-Item -ItemType Directory -Path $BUILD_DIR
}

# Install dev dependencies (including PyInstaller) using uv
Write-Host "Installing dependencies including PyInstaller..."
uv sync --extra dev

# Read the master version from video_grouper/version.py
$VERSION = (uv run python -c "from video_grouper.version import VERSION; print(VERSION)").Trim()
if (-not $VERSION) {
    Write-Error "Failed to read version from video_grouper/version.py"
    exit 1
}
Write-Host "Building version: $VERSION"

# Generate YouTube OAuth secrets file from environment variables (set by GitHub Actions)
$SECRETS_FILE = Join-Path $SCRIPT_DIR "video_grouper\utils\_youtube_secrets.py"
$YT_CLIENT_ID = $env:SOCCER_CAM_YT_CLIENT_ID
$YT_CLIENT_SECRET = $env:SOCCER_CAM_YT_CLIENT_SECRET
if ($YT_CLIENT_ID -and $YT_CLIENT_SECRET) {
    Write-Host "Injecting YouTube OAuth credentials..."
    @"
# Auto-generated by build-installer.ps1 -- do not commit
YT_CLIENT_ID = "$YT_CLIENT_ID"
YT_CLIENT_SECRET = "$YT_CLIENT_SECRET"
"@ | Set-Content -Path $SECRETS_FILE -Encoding UTF8
} else {
    Write-Host "WARNING: SOCCER_CAM_YT_CLIENT_ID / SOCCER_CAM_YT_CLIENT_SECRET not set."
    Write-Host "YouTube OAuth will not work in the built binary."
}

# Generate TTT config file from environment variables
$TTT_CONFIG_FILE = Join-Path $SCRIPT_DIR "video_grouper\utils\_ttt_config.py"
$TTT_SUPABASE_URL = $env:SOCCER_CAM_TTT_SUPABASE_URL
$TTT_ANON_KEY = $env:SOCCER_CAM_TTT_ANON_KEY
$TTT_API_BASE_URL = $env:SOCCER_CAM_TTT_API_BASE_URL
if ($TTT_SUPABASE_URL -and $TTT_ANON_KEY -and $TTT_API_BASE_URL) {
    Write-Host "Injecting TTT configuration..."
    @"
# Auto-generated by build-installer.ps1 -- do not commit
TTT_SUPABASE_URL = "$TTT_SUPABASE_URL"
TTT_ANON_KEY = "$TTT_ANON_KEY"
TTT_API_BASE_URL = "$TTT_API_BASE_URL"
"@ | Set-Content -Path $TTT_CONFIG_FILE -Encoding UTF8
} else {
    Write-Host "INFO: SOCCER_CAM_TTT_* not set. Using production TTT defaults."
}

# Generate PlayMetrics Firebase key file (public project-level key, safe to embed)
$PM_SECRETS_FILE = Join-Path $SCRIPT_DIR "video_grouper\utils\_playmetrics_secrets.py"
$PM_FIREBASE_KEY = if ($env:SOCCER_CAM_PM_FIREBASE_KEY) { $env:SOCCER_CAM_PM_FIREBASE_KEY } else { "AIzaSyBEB_rFRGuLJja2vzeDCa7J1NZp0E7RN4U" }
Write-Host "Injecting PlayMetrics Firebase key..."
@"
# Auto-generated by build-installer.ps1 -- do not commit
PLAYMETRICS_FIREBASE_WEB_API_KEY = "$PM_FIREBASE_KEY"
"@ | Set-Content -Path $PM_SECRETS_FILE -Encoding UTF8

# Check for NSIS installation
$NSIS_PATH = "C:\Program Files (x86)\NSIS\makensis.exe"
if (-not (Test-Path $NSIS_PATH)) {
    Write-Host "NSIS not found at $NSIS_PATH"
    Write-Host "Please install NSIS from https://nsis.sourceforge.io/Download"
    exit 1
}

# Build service executable from spec file (source of truth for PyInstaller config)
Write-Host "Building service executable..."
uv run pyinstaller --noconfirm --distpath=$DIST_DIR --workpath=$BUILD_DIR VideoGrouperService.spec

# Build tray agent executable from spec file
Write-Host "Building tray agent executable..."
uv run pyinstaller --noconfirm --distpath=$DIST_DIR --workpath=$BUILD_DIR VideoGrouperTray.spec

# Build installer
Write-Host "Building installer..."
& $NSIS_PATH "/DVERSION=$VERSION" "/DBUILD_NUMBER=$BUILD_NUMBER" $INSTALLER_SCRIPT

Write-Host "Build complete! Check the video_grouper/dist directory for the installer." 