services:
  video-grouper:
    build:
      context: .
      dockerfile: ./video_grouper/Dockerfile
      args:
        VERSION: "1.0.0"
        BUILD_NUMBER: "1"
    volumes:
      - ./shared_data:/shared_data
      - ./video_grouper/config.ini:/app/config.ini
    environment:
      - PYTHONUNBUFFERED=1

  dahua-emulator:
    profiles:
      - dahua
    build:
      context: .
      dockerfile: tests/camera_emulator/Dockerfile
    environment:
      - CAMERA_TYPE=dahua
      - USERNAME=admin
      - PASSWORD=admin
    volumes:
      - ./tests/e2e/test_clips:/clips:ro
    ports:
      - "9554:80"

  reolink-emulator:
    profiles:
      - reolink
    build:
      context: .
      dockerfile: tests/camera_emulator/Dockerfile
    environment:
      - CAMERA_TYPE=reolink
      - USERNAME=admin
      - PASSWORD=admin
    volumes:
      - ./tests/e2e/test_clips:/clips:ro
    ports:
      - "9555:80"
