[project]
name = "video-grouper"
version = "0.1.0"
description = "A tool to automatically group and process video files from a security camera."
authors = [
    {name = "Your Name", email = "you@example.com"},
]
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "httpx>=0.25.0",
    "aiofiles>=23.2.1",
    "pytz>=2024.1",
    "pywinauto>=0.6.8",
    "google-api-python-client>=2.100.0",
    "google-auth-oauthlib>=1.0.0",
    "requests>=2.31.0",
    "icalendar>=6.3.1",
    "beautifulsoup4>=4.13.4",
    "cryptography>=42.0.0",
    "pydantic>=2.11.7",
]

[project.optional-dependencies]
tray = [
    "PyQt6>=6.6.0",
    "pywin32>=306",
]
service = [
    "pywin32>=306",
]
dev = [
    "pytest>=7.4.3",
    "pytest-asyncio>=0.21.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build" 
