# -*- mode: python ; coding: utf-8 -*-
"""Multi-target PyInstaller spec — service + tray share one _internal/.

Both the Windows service and the system tray import the same large
chunk of soccer-cam (task_processors, integrations, web routers).
Building them as separate `pyinstaller --onedir` outputs ships two
copies of the entire dependency tree (~1.8 GB raw, ~370 MB
compressed).  This spec runs one Analysis per entry point, MERGEs
the shared bits, and emits a single COLLECT — so dist/VideoGrouper/
contains both .exes plus one shared _internal/.

Excludes drop the training-only ML stack (torch / ultralytics / scipy
/ matplotlib / sympy / networkx). Inference modules need numpy +
onnxruntime + cv2 only — those stay bundled.

Build:
    uv run pyinstaller --noconfirm \
        --distpath video_grouper/dist \
        --workpath video_grouper/build \
        video_grouper/installer/VideoGrouper.spec
"""

import os
import sys

# PyInstaller resolves relative paths in a .spec file relative to the
# spec's own directory. The spec lives at video_grouper/installer/, so
# the entry points and icon live one directory up.
SPEC_DIR = os.path.dirname(os.path.abspath(SPEC))
PROJECT_ROOT = os.path.abspath(os.path.join(SPEC_DIR, "..", ".."))
SERVICE_MAIN = os.path.join(PROJECT_ROOT, "video_grouper", "service", "main.py")
TRAY_MAIN = os.path.join(PROJECT_ROOT, "video_grouper", "tray", "main.py")
ICON_PATH = os.path.join(PROJECT_ROOT, "video_grouper", "icon.ico")

# Make video_grouper importable so we can read version.py without
# importing the rest of the package (which would pull in PyQt6 / cv2
# / etc. just for a string constant).
sys.path.insert(0, PROJECT_ROOT)
from video_grouper.version import VERSION, BUILD_NUMBER  # noqa: E402


def _version_tuple() -> tuple[int, int, int, int]:
    """Convert VERSION ('0.3.7') + BUILD_NUMBER ('0') to the 4-int
    Windows PE version format."""
    parts = [int(p) for p in VERSION.split(".")]
    while len(parts) < 3:
        parts.append(0)
    parts.append(int(BUILD_NUMBER))
    return tuple(parts[:4])


def _write_versioninfo(out_path: str, internal_name: str, original_filename: str) -> str:
    """Emit a PyInstaller-compatible version resource file.

    Without this, the built .exe ships with empty FileVersion /
    ProductVersion fields -- Get-Item .VersionInfo.FileVersion reads
    as blank, which breaks anyone trying to verify the install or
    pin a version from outside the process (registry DisplayVersion
    is set by NSIS, but the exe metadata itself was empty).
    """
    fv = _version_tuple()
    body = f"""# Auto-generated by VideoGrouper.spec at build time.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={fv!r},
    prodvers={fv!r},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0),
  ),
  kids=[
    StringFileInfo([
      StringTable(
        '040904B0',
        [
          StringStruct('CompanyName', 'VideoGrouper'),
          StringStruct('FileDescription', 'VideoGrouper Service and Tray Agent'),
          StringStruct('FileVersion', '{VERSION}.{BUILD_NUMBER}'),
          StringStruct('InternalName', '{internal_name}'),
          StringStruct('LegalCopyright', 'Copyright (c) 2026 VideoGrouper'),
          StringStruct('OriginalFilename', '{original_filename}'),
          StringStruct('ProductName', 'VideoGrouper'),
          StringStruct('ProductVersion', '{VERSION}.{BUILD_NUMBER}'),
        ],
      ),
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])]),
  ],
)
"""
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(body)
    return out_path


# Workpath gets cleaned by --noconfirm so we generate fresh on every
# build. Two files because the two exes have different
# InternalName/OriginalFilename.
_BUILD_DIR = os.path.join(PROJECT_ROOT, "video_grouper", "build")
os.makedirs(_BUILD_DIR, exist_ok=True)
SERVICE_VERSION_FILE = _write_versioninfo(
    os.path.join(_BUILD_DIR, "service_version_info.txt"),
    internal_name="VideoGrouperService",
    original_filename="VideoGrouperService.exe",
)
TRAY_VERSION_FILE = _write_versioninfo(
    os.path.join(_BUILD_DIR, "tray_version_info.txt"),
    internal_name="VideoGrouperTray",
    original_filename="VideoGrouperTray.exe",
)

# Training stack (torch alone is 3.85 GB) — never used at runtime
# in either the service or the tray.
TRAINING_EXCLUDES = [
    "torch",
    "torchvision",
    "ultralytics",
    "ultralytics_thop",
    # torch's transitive bloat
    "scipy",
    "matplotlib",
    "sympy",
    "networkx",
]

# Tray-only additional excludes. The tray's only ball-tracking
# responsibility is the autocam_gui provider, which spawns an external
# Once Sport AutoCam GUI process — it never imports the inference
# stack itself. The homegrown provider lives entirely in the service
# (which DOES bundle these), so leaving them out of the tray drops
# ~500 MB AND sidesteps a DLL initialization conflict between
# onnxruntime's pybind11 .pyd and PyQt6's bundled MSVCP140.dll that
# crashed the tray on jared's RDP session (2026-05-09 incident).
# The service still has cv2/onnxruntime/av — those are excluded
# only from the tray.
#
# googleapiclient stays bundled: the tray imports authenticate_youtube
# at module top for the YouTube re-auth menu action, so dropping it
# would crash the tray at startup with ModuleNotFoundError.
TRAY_EXCLUDES = TRAINING_EXCLUDES + [
    "onnxruntime",
    "cv2",
    "av",
]

# Bundle the base YOLO person model the phase_detect step's player-on-field
# curve uses, so game-phase detection works out of the box. The model is
# committed via Git LFS (see .gitattributes); a checkout without `git lfs pull`
# leaves a ~130-byte pointer file, which must NOT be bundled (it isn't the
# model). Include the weights only when the real bytes are present — else the
# step degrades to an ok=false artifact at runtime (resolve_person_model / the
# PersonModelUnavailable path). The AGPL-3.0 license ships beside it.
_PHASE_MODEL = os.path.join(PROJECT_ROOT, "video_grouper", "models", "person.onnx")
_PHASE_MODEL_LICENSE = os.path.join(
    PROJECT_ROOT, "video_grouper", "models", "LICENSE-AGPL-3.0.txt"
)
PHASE_MODEL_DATAS = []
if os.path.exists(_PHASE_MODEL) and os.path.getsize(_PHASE_MODEL) > 1_000_000:
    PHASE_MODEL_DATAS.append((_PHASE_MODEL, "models"))
    if os.path.exists(_PHASE_MODEL_LICENSE):
        PHASE_MODEL_DATAS.append((_PHASE_MODEL_LICENSE, "models"))
    print(
        f"VideoGrouper.spec: bundling person model "
        f"({os.path.getsize(_PHASE_MODEL)} bytes) from {_PHASE_MODEL}"
    )
else:
    print(
        "VideoGrouper.spec: WARNING person model missing or an un-pulled LFS "
        f"pointer at {_PHASE_MODEL}; phase detection will degrade to ok=false. "
        "Run `git lfs pull` before building a release."
    )

a_service = Analysis(
    [SERVICE_MAIN],
    pathex=[],
    binaries=[],
    datas=PHASE_MODEL_DATAS,
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=TRAINING_EXCLUDES,
    noarchive=False,
    optimize=0,
)

a_tray = Analysis(
    [TRAY_MAIN],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=TRAY_EXCLUDES,
    noarchive=False,
    optimize=0,
)

# Deduplicate: tag every shared dep as belonging to the service so the
# tray Analysis only carries what's exclusive to it.
MERGE(
    (a_service, "VideoGrouperService", "VideoGrouperService"),
    (a_tray, "VideoGrouperTray", "VideoGrouperTray"),
)

pyz_service = PYZ(a_service.pure)
pyz_tray = PYZ(a_tray.pure)

exe_service = EXE(
    pyz_service,
    a_service.scripts,
    [],
    exclude_binaries=True,
    name="VideoGrouperService",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    icon=ICON_PATH,
    version=SERVICE_VERSION_FILE,
)

exe_tray = EXE(
    pyz_tray,
    a_tray.scripts,
    [],
    exclude_binaries=True,
    name="VideoGrouperTray",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    icon=ICON_PATH,
    version=TRAY_VERSION_FILE,
)

coll = COLLECT(
    exe_service,
    a_service.binaries,
    a_service.datas,
    exe_tray,
    a_tray.binaries,
    a_tray.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name="VideoGrouper",
)
