name: Build Windows Service

on:
  push:
    tags:
      - 'v*'
    branches: [ main ]
    paths:
      - 'video_grouper/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'video_grouper/**'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for versioning
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r video_grouper/requirements.txt
        
    - name: Get version from tag
      id: get_version
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        $version = $env:GITHUB_REF -replace 'refs/tags/v', ''
        echo "VERSION=$version" >> $env:GITHUB_ENV
        echo "BUILD_NUMBER=0" >> $env:GITHUB_ENV
        
    - name: Get version from commit
      id: get_version_commit
      if: startsWith(github.ref, 'refs/heads/')
      run: |
        $commitCount = git rev-list --count HEAD
        $version = "0.0.0"
        echo "VERSION=$version" >> $env:GITHUB_ENV
        echo "BUILD_NUMBER=$commitCount" >> $env:GITHUB_ENV
        
    - name: Update version info
      run: |
        (Get-Content video_grouper/version.py) -replace 'VERSION = "[^"]*"', "VERSION = `"$env:VERSION`"" | Set-Content video_grouper/version.py
        (Get-Content video_grouper/version.py) -replace 'BUILD_NUMBER = "[^"]*"', "BUILD_NUMBER = `"$env:BUILD_NUMBER`"" | Set-Content video_grouper/version.py
        
    - name: Build service executable
      run: |
        pyinstaller --noconfirm --onefile --windowed --icon=video_grouper/icon.ico --name=VideoGrouperService video_grouper/service_wrapper.py
        
    - name: Build tray agent executable
      run: |
        pyinstaller --noconfirm --onefile --windowed --icon=video_grouper/icon.ico --name=tray_agent video_grouper/tray_agent.py
        
    - name: Install NSIS
      uses: medzin/install-nsis@v3
      
    - name: Build installer
      run: |
        makensis /DVERSION=$env:VERSION /DBUILD_NUMBER=$env:BUILD_NUMBER video_grouper/installer.nsi
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: VideoGrouper-${{ env.VERSION }}
        path: |
          dist/VideoGrouperService.exe
          dist/tray_agent.exe
          dist/VideoGrouperSetup.exe 