name: Build Windows Service

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build Windows Service
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install uv
      run: |
        python -m pip install --upgrade pip
        pip install uv

    - name: Install dependencies
      run: |
        uv sync --extra dev --extra tray --extra service

    - name: Extract version information
      id: version
      run: |
        if ($env:GITHUB_REF -like 'refs/tags/*') {
          $VERSION = $env:GITHUB_REF -replace 'refs/tags/v', ''
          $BUILD_NUMBER = '0'
        } else {
          $VERSION = '0.0.0'
          $BUILD_NUMBER = git rev-list --count HEAD
        }
        echo "VERSION=$VERSION" >> $env:GITHUB_ENV
        echo "BUILD_NUMBER=$BUILD_NUMBER" >> $env:GITHUB_ENV

    - name: Update version.py
      run: |
        echo "VERSION = '${{ env.VERSION }}'" > video_grouper/version.py
        echo "BUILD_NUMBER = '${{ env.BUILD_NUMBER }}'" >> video_grouper/version.py

    - name: Build service executable
      run: |
        uv run pyinstaller --noconfirm --onefile --windowed --icon=video_grouper/icon.ico --name=VideoGrouperService --distpath=video_grouper/dist --workpath=video_grouper/build video_grouper/service/main.py

    - name: Build tray agent executable
      run: |
        uv run pyinstaller --noconfirm --onefile --windowed --icon=video_grouper/icon.ico --name=VideoGrouperTray --distpath=video_grouper/dist --workpath=video_grouper/build video_grouper/tray/main.py

    - name: Build installer
      uses: joncloud/makensis-action@v4.1
      with:
        script-file: video_grouper/installer/installer.nsi
        arguments: "/DVERSION=${{ env.VERSION }} /DBUILD_NUMBER=${{ env.BUILD_NUMBER }}"

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: VideoGrouper-${{ env.VERSION }}-${{ env.BUILD_NUMBER }}
        path: |
          video_grouper/dist/VideoGrouperSetup.exe
          video_grouper/dist/VideoGrouperService.exe
          video_grouper/dist/VideoGrouperTray.exe
