name: Build Windows Service

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r video_grouper/requirements.txt
        pip install pyinstaller

    - name: Extract version information
      id: version
      run: |
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          VERSION=${GITHUB_REF#refs/tags/v}
          BUILD_NUMBER=0
        else
          VERSION=0.0.0
          BUILD_NUMBER=$(git rev-list --count HEAD)
        fi
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "BUILD_NUMBER=$BUILD_NUMBER" >> $GITHUB_ENV

    - name: Update version.py
      run: |
        echo "VERSION = '${{ env.VERSION }}'" > video_grouper/version.py
        echo "BUILD_NUMBER = '${{ env.BUILD_NUMBER }}'" >> video_grouper/version.py

    - name: Build service executable
      run: |
        pyinstaller --noconfirm --onefile --windowed --icon=video_grouper/icon.ico --name=VideoGrouperService --distpath=video_grouper/dist --workpath=video_grouper/build video_grouper/service_wrapper.py

    - name: Build tray agent executable
      run: |
        pyinstaller --noconfirm --onefile --windowed --icon=video_grouper/icon.ico --name=tray_agent --distpath=video_grouper/dist --workpath=video_grouper/build video_grouper/tray_agent.py

    - name: Install NSIS
      uses: medzin/install-nsis@v3

    - name: Build installer
      run: |
        makensis /DVERSION=${{ env.VERSION }} /DBUILD_NUMBER=${{ env.BUILD_NUMBER }} video_grouper/installer.nsi

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: VideoGrouper-${{ env.VERSION }}-${{ env.BUILD_NUMBER }}
        path: |
          video_grouper/dist/VideoGrouperSetup.exe
          video_grouper/dist/VideoGrouperService.exe
          video_grouper/dist/tray_agent.exe 