name: Update Release

on:
  release:
    types: [created]

jobs:
  update-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract version
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "BUILD_NUMBER=0" >> $GITHUB_ENV

      - name: Wait for Windows build
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.ref }}
          check-name: 'Build Windows Service'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
          allowed-conclusions: success

      - name: Get workflow run ID
        id: get_run_id
        uses: actions/github-script@v7
        with:
          script: |
            const { data } = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'build-windows-service.yml',
              head_sha: context.sha,
              event: 'create',
              status: 'completed',
              conclusion: 'success',
              per_page: 1
            });
            
            console.log('Workflow runs:', JSON.stringify(data, null, 2));
            
            if (!data.workflow_runs || data.workflow_runs.length === 0) {
              throw new Error('No successful workflow runs found');
            }
            
            const runId = data.workflow_runs[0].id;
            console.log('Run ID:', runId);
            core.setOutput('run_id', runId);
            return runId;

      - name: Download Windows artifacts
        uses: actions/download-artifact@v4
        with:
          name: VideoGrouper-${{ env.VERSION }}-${{ env.BUILD_NUMBER }}
          path: artifacts
          run-id: ${{ steps.get_run_id.outputs.run_id }}

      - name: Update Release
        uses: softprops/action-gh-release@v1
        with:
          release_id: ${{ github.event.release.id }}
          body: |
            # VideoGrouper ${{ env.VERSION }}
            
            ## Windows Installer
            Download and run VideoGrouperSetup.exe to install the Windows application.
            
            ## Docker Container
            Pull the Docker image:
            ```bash
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/video-grouper:${{ env.VERSION }}
            ```
            
            See [Docker Hub](https://hub.docker.com/r/${{ secrets.DOCKERHUB_USERNAME }}/video-grouper) for more details.
            
            ## Changes
            See the commit history for details.
          files: |
            artifacts/VideoGrouperSetup.exe
            artifacts/VideoGrouperService.exe
            artifacts/tray_agent.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
